import Head from 'next/head'
import Lorem from '../components/home/lorem';
import Order from '../components/order/order';

const Home = () => {
  return (
      <>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main>
          <Lorem/>
          <Order/>
        </main>
      </>
  )
}

export default Home