import Head from 'next/head'
import Image from 'next/image'
import Header from '../components/header/header';
import Lorem from '../components/home/lorem';
import Order from '../components/order/order';
import Footer from '../components/footer/footer';

const Home = () => {
  return (
      <>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Header/>
        <main>
          
          <Lorem/>
          <Order/>
          
        </main>
        <Footer/>
      </>
  )
}

export default Home